version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.10.0
  aws-ecs: circleci/aws-ecs@1.2.0
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          path: .
          dockerfile: docker/php/Dockerfile
          region: AWS_REGION
          repo: app
          tag: 'latest'
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: 'ecssample-task'
          cluster-name: 'test-cluster'
          service-name: 'app-service'
          container-image-name-updates: 'container=app-service,tag=lastest'