version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.10.0
  aws-ecs: circleci/aws-ecs@1.2.0
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: ACCESS_KEY_ID
          aws-secret-access-key: SECRET_ACCESS_KEY
          path: .
          dockerfile: docker/php/Dockerfile
          region: AWS_REGION
          repo: app
          tag: 'latest'
      - aws-ecs/deploy-service-update:
          aws-access-key-id: ACCESS_KEY_ID
          aws-secret-access-key: SECRET_ACCESS_KEY
          requires:
            - aws-ecr/build-and-push-image
          family: 'app-service'
          cluster-name: 'test-cluster'
          container-image-name-updates: 'container=app-service,tag=lastest'